package com.mms.cloud.utils;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.mms.cloud.dto.OrderStatusMonitorDTO;

public class ProvinceMap {
	
	public static Map<String,Integer> province_nomarl = new HashMap<String,Integer>();
	public static Map<String,Integer> province_yujing = new HashMap<String,Integer>();
	public static Map<String,Integer> province_jinggao = new HashMap<String,Integer>();
	
	public static Map<String,List<OrderStatusMonitorDTO>> province_nomarl_order = new HashMap<String,List<OrderStatusMonitorDTO>>();
	public static Map<String,List<OrderStatusMonitorDTO>> province_yujing_order = new HashMap<String,List<OrderStatusMonitorDTO>>();
	public static Map<String,List<OrderStatusMonitorDTO>> province_jinggao_order = new HashMap<String,List<OrderStatusMonitorDTO>>();
	
	public static List<OrderStatusMonitorDTO> china_nomarl_order = new ArrayList<OrderStatusMonitorDTO>();
	public static List<OrderStatusMonitorDTO> china_yujing_order = new ArrayList<OrderStatusMonitorDTO>();
	public static List<OrderStatusMonitorDTO> china_jinggao_order = new ArrayList<OrderStatusMonitorDTO>();
	
	public static Integer china_namarl = 0;
	public static Integer china_yujing = 0;
	public static Integer china_jinggao = 0;
    		
	static{
		province_nomarl.put("四川", 0);
		province_nomarl.put("贵州", 0);
		province_nomarl.put("云南", 0);
		province_nomarl.put("西藏", 0);
		province_nomarl.put("陕西", 0);
		province_nomarl.put("甘肃", 0);
		province_nomarl.put("青海", 0);
		province_nomarl.put("宁夏", 0);
		province_nomarl.put("新疆", 0);
		province_nomarl.put("台湾", 0);
		province_nomarl.put("重庆", 0);
		province_nomarl.put("湖南", 0);
		province_nomarl.put("湖北", 0);
		province_nomarl.put("河南", 0);
		province_nomarl.put("海南", 0);
		province_nomarl.put("广西", 0);
		province_nomarl.put("广东", 0);
		province_nomarl.put("山东", 0);
		province_nomarl.put("江西", 0);
		province_nomarl.put("福建", 0);
		province_nomarl.put("安徽", 0);
		province_nomarl.put("浙江", 0);
		province_nomarl.put("江苏", 0);
		province_nomarl.put("上海", 0);
		province_nomarl.put("黑龙江", 0);
		province_nomarl.put("吉林", 0);
		province_nomarl.put("辽宁", 0);
		province_nomarl.put("内蒙古", 0);
		province_nomarl.put("山西", 0);
		province_nomarl.put("河北", 0);
		province_nomarl.put("天津", 0);
		province_nomarl.put("北京", 0);
		
		province_yujing.put("四川", 0);
		province_yujing.put("贵州", 0);
		province_yujing.put("云南", 0);
		province_yujing.put("西藏", 0);
		province_yujing.put("陕西", 0);
		province_yujing.put("甘肃", 0);
		province_yujing.put("青海", 0);
		province_yujing.put("宁夏", 0);
		province_yujing.put("新疆", 0);
		province_yujing.put("台湾", 0);
		province_yujing.put("重庆", 0);
		province_yujing.put("湖南", 0);
		province_yujing.put("湖北", 0);
		province_yujing.put("河南", 0);
		province_yujing.put("海南", 0);
		province_yujing.put("广西", 0);
		province_yujing.put("广东", 0);
		province_yujing.put("山东", 0);
		province_yujing.put("江西", 0);
		province_yujing.put("福建", 0);
		province_yujing.put("安徽", 0);
		province_yujing.put("浙江", 0);
		province_yujing.put("江苏", 0);
		province_yujing.put("上海", 0);
		province_yujing.put("黑龙江", 0);
		province_yujing.put("吉林", 0);
		province_yujing.put("辽宁", 0);
		province_yujing.put("内蒙古", 0);
		province_yujing.put("山西", 0);
		province_yujing.put("河北", 0);
		province_yujing.put("天津", 0);
		province_yujing.put("北京", 0);
		
		province_jinggao.put("四川", 0);
		province_jinggao.put("贵州", 0);
		province_jinggao.put("云南", 0);
		province_jinggao.put("西藏", 0);
		province_jinggao.put("陕西", 0);
		province_jinggao.put("甘肃", 0);
		province_jinggao.put("青海", 0);
		province_jinggao.put("宁夏", 0);
		province_jinggao.put("新疆", 0);
		province_jinggao.put("台湾", 0);
		province_jinggao.put("重庆", 0);
		province_jinggao.put("湖南", 0);
		province_jinggao.put("湖北", 0);
		province_jinggao.put("河南", 0);
		province_jinggao.put("海南", 0);
		province_jinggao.put("广西", 0);
		province_jinggao.put("广东", 0);
		province_jinggao.put("山东", 0);
		province_jinggao.put("江西", 0);
		province_jinggao.put("福建", 0);
		province_jinggao.put("安徽", 0);
		province_jinggao.put("浙江", 0);
		province_jinggao.put("江苏", 0);
		province_jinggao.put("上海", 0);
		province_jinggao.put("黑龙江", 0);
		province_jinggao.put("吉林", 0);
		province_jinggao.put("辽宁", 0);
		province_jinggao.put("内蒙古", 0);
		province_jinggao.put("山西", 0);
		province_jinggao.put("河北", 0);
		province_jinggao.put("天津", 0);
		province_jinggao.put("北京", 0);
		
		province_nomarl_order.put("四川", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("贵州", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("云南", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("西藏", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("陕西", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("甘肃", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("青海", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("宁夏", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("新疆", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("台湾", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("重庆", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("湖南", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("湖北", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("河南", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("海南", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("广西", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("广东", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("山东", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("江西", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("福建", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("安徽", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("浙江", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("江苏", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("上海", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("黑龙江", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("吉林", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("辽宁", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("内蒙古", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("山西", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("河北", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("天津", new ArrayList<OrderStatusMonitorDTO>());
		province_nomarl_order.put("北京", new ArrayList<OrderStatusMonitorDTO>());
		
		province_yujing_order.put("四川", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("贵州", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("云南", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("西藏", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("陕西", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("甘肃", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("青海", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("宁夏", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("新疆", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("台湾", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("重庆", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("湖南", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("湖北", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("河南", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("海南", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("广西", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("广东", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("山东", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("江西", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("福建", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("安徽", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("浙江", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("江苏", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("上海", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("黑龙江", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("吉林", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("辽宁", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("内蒙古", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("山西", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("河北", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("天津", new ArrayList<OrderStatusMonitorDTO>());
		province_yujing_order.put("北京", new ArrayList<OrderStatusMonitorDTO>());
		
		province_jinggao_order.put("四川", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("贵州", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("云南", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("西藏", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("陕西", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("甘肃", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("青海", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("宁夏", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("新疆", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("台湾", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("重庆", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("湖南", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("湖北", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("河南", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("海南", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("广西", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("广东", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("山东", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("江西", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("福建", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("安徽", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("浙江", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("江苏", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("上海", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("黑龙江", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("吉林", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("辽宁", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("内蒙古", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("山西", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("河北", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("天津", new ArrayList<OrderStatusMonitorDTO>());
		province_jinggao_order.put("北京", new ArrayList<OrderStatusMonitorDTO>());
	}
	
	public  static void reset(String province){
		if(province == null || province.equals("")|| province.equals("china")){
			province_nomarl.put("四川", 0);
			province_nomarl.put("贵州", 0);
			province_nomarl.put("云南", 0);
			province_nomarl.put("西藏", 0);
			province_nomarl.put("陕西", 0);
			province_nomarl.put("甘肃", 0);
			province_nomarl.put("青海", 0);
			province_nomarl.put("宁夏", 0);
			province_nomarl.put("新疆", 0);
			province_nomarl.put("台湾", 0);
			province_nomarl.put("重庆", 0);
			province_nomarl.put("湖南", 0);
			province_nomarl.put("湖北", 0);
			province_nomarl.put("河南", 0);
			province_nomarl.put("海南", 0);
			province_nomarl.put("广西", 0);
			province_nomarl.put("广东", 0);
			province_nomarl.put("山东", 0);
			province_nomarl.put("江西", 0);
			province_nomarl.put("福建", 0);
			province_nomarl.put("安徽", 0);
			province_nomarl.put("浙江", 0);
			province_nomarl.put("江苏", 0);
			province_nomarl.put("上海", 0);
			province_nomarl.put("黑龙江", 0);
			province_nomarl.put("吉林", 0);
			province_nomarl.put("辽宁", 0);
			province_nomarl.put("内蒙古", 0);
			province_nomarl.put("山西", 0);
			province_nomarl.put("河北", 0);
			province_nomarl.put("天津", 0);
			province_nomarl.put("北京", 0);
			
			province_yujing.put("四川", 0);
			province_yujing.put("贵州", 0);
			province_yujing.put("云南", 0);
			province_yujing.put("西藏", 0);
			province_yujing.put("陕西", 0);
			province_yujing.put("甘肃", 0);
			province_yujing.put("青海", 0);
			province_yujing.put("宁夏", 0);
			province_yujing.put("新疆", 0);
			province_yujing.put("台湾", 0);
			province_yujing.put("重庆", 0);
			province_yujing.put("湖南", 0);
			province_yujing.put("湖北", 0);
			province_yujing.put("河南", 0);
			province_yujing.put("海南", 0);
			province_yujing.put("广西", 0);
			province_yujing.put("广东", 0);
			province_yujing.put("山东", 0);
			province_yujing.put("江西", 0);
			province_yujing.put("福建", 0);
			province_yujing.put("安徽", 0);
			province_yujing.put("浙江", 0);
			province_yujing.put("江苏", 0);
			province_yujing.put("上海", 0);
			province_yujing.put("黑龙江", 0);
			province_yujing.put("吉林", 0);
			province_yujing.put("辽宁", 0);
			province_yujing.put("内蒙古", 0);
			province_yujing.put("山西", 0);
			province_yujing.put("河北", 0);
			province_yujing.put("天津", 0);
			province_yujing.put("北京", 0);
			
			province_jinggao.put("四川", 0);
			province_jinggao.put("贵州", 0);
			province_jinggao.put("云南", 0);
			province_jinggao.put("西藏", 0);
			province_jinggao.put("陕西", 0);
			province_jinggao.put("甘肃", 0);
			province_jinggao.put("青海", 0);
			province_jinggao.put("宁夏", 0);
			province_jinggao.put("新疆", 0);
			province_jinggao.put("台湾", 0);
			province_jinggao.put("重庆", 0);
			province_jinggao.put("湖南", 0);
			province_jinggao.put("湖北", 0);
			province_jinggao.put("河南", 0);
			province_jinggao.put("海南", 0);
			province_jinggao.put("广西", 0);
			province_jinggao.put("广东", 0);
			province_jinggao.put("山东", 0);
			province_jinggao.put("江西", 0);
			province_jinggao.put("福建", 0);
			province_jinggao.put("安徽", 0);
			province_jinggao.put("浙江", 0);
			province_jinggao.put("江苏", 0);
			province_jinggao.put("上海", 0);
			province_jinggao.put("黑龙江", 0);
			province_jinggao.put("吉林", 0);
			province_jinggao.put("辽宁", 0);
			province_jinggao.put("内蒙古", 0);
			province_jinggao.put("山西", 0);
			province_jinggao.put("河北", 0);
			province_jinggao.put("天津", 0);
			province_jinggao.put("北京", 0);
			
			china_namarl = 0;
			china_yujing = 0;
			china_jinggao = 0;
			
			province_nomarl_order.put("四川", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("贵州", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("云南", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("西藏", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("陕西", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("甘肃", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("青海", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("宁夏", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("新疆", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("台湾", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("重庆", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("湖南", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("湖北", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("河南", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("海南", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("广西", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("广东", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("山东", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("江西", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("福建", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("安徽", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("浙江", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("江苏", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("上海", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("黑龙江", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("吉林", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("辽宁", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("内蒙古", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("山西", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("河北", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("天津", new ArrayList<OrderStatusMonitorDTO>());
			province_nomarl_order.put("北京", new ArrayList<OrderStatusMonitorDTO>());
			
			province_yujing_order.put("四川", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("贵州", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("云南", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("西藏", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("陕西", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("甘肃", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("青海", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("宁夏", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("新疆", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("台湾", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("重庆", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("湖南", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("湖北", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("河南", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("海南", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("广西", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("广东", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("山东", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("江西", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("福建", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("安徽", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("浙江", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("江苏", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("上海", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("黑龙江", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("吉林", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("辽宁", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("内蒙古", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("山西", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("河北", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("天津", new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put("北京", new ArrayList<OrderStatusMonitorDTO>());
			
			province_jinggao_order.put("四川", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("贵州", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("云南", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("西藏", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("陕西", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("甘肃", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("青海", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("宁夏", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("新疆", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("台湾", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("重庆", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("湖南", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("湖北", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("河南", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("海南", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("广西", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("广东", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("山东", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("江西", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("福建", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("安徽", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("浙江", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("江苏", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("上海", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("黑龙江", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("吉林", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("辽宁", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("内蒙古", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("山西", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("河北", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("天津", new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put("北京", new ArrayList<OrderStatusMonitorDTO>());
			
			china_nomarl_order = new ArrayList<OrderStatusMonitorDTO>();
			china_yujing_order = new ArrayList<OrderStatusMonitorDTO>();
			china_jinggao_order = new ArrayList<OrderStatusMonitorDTO>();
		}else{
			province_nomarl.put(province, 0);
			province_yujing.put(province, 0);
			province_jinggao.put(province, 0);
			province_nomarl_order.put(province, new ArrayList<OrderStatusMonitorDTO>());
			province_yujing_order.put(province, new ArrayList<OrderStatusMonitorDTO>());
			province_jinggao_order.put(province, new ArrayList<OrderStatusMonitorDTO>());
		}
		
	}
}
